import type { CLIModel, Command } from "./types";

function escapeTroff(text: unknown): string {
  // Handle null/undefined/non-string values
  if (text == null) return '';
  const str = String(text);
  // Escape backslashes first, then handle lines starting with dots
  return str
    .replace(/\\/g, '\\\\')
    .replace(/^\./g, '\\&.')
    .replace(/\n\./g, '\n\\&.');
}

export function generateManPage(model: CLIModel): string {
  const date = new Date().toISOString().split("T")[0];
  const nameUpper = model.name.toUpperCase();

  const sections: string[] = [
    // Header
    `.TH ${nameUpper} 1 "${date}" "${escapeTroff(model.version)}" "${escapeTroff(model.name)} Manual"`,

    // Name
    `.SH NAME`,
    `${escapeTroff(model.name)} \\- ${escapeTroff(model.description)}`,

    // Synopsis
    `.SH SYNOPSIS`,
    `.B ${model.name}`,
    `.I command`,
    `.RI [ options ]`,

    // Description
    `.SH DESCRIPTION`,
    `.B ${model.name}`,
    `is a command-line interface for ${escapeTroff(model.description)}.`,
    `It provides access to the API at ${escapeTroff(model.baseUrl)}.`,

    // Commands
    `.SH COMMANDS`,
    generateConfigCommandsMan(model.name),
    ...model.resources.map((r) => generateResourceMan(r.name, r.description, r.commands, model.name)),

    // Global Options
    `.SH GLOBAL OPTIONS`,
    `.TP`,
    `.BR \\-\\-token " " \\fItoken\\fR`,
    `API authentication token. Can also be set via ${nameUpper.replace(/-/g, "_")}_TOKEN environment variable or config file.`,
    `.TP`,
    `.BR \\-\\-output " " \\fIformat\\fR`,
    `Output format. Valid values: json, table. Default: json.`,
    `.TP`,
    `.BR \\-\\-header " " \\fIheader\\fR`,
    `Custom header in "Name: Value" format.`,
    `.TP`,
    `.BR \\-\\-help`,
    `Show help message and exit.`,
    `.TP`,
    `.BR \\-\\-version`,
    `Show version information and exit.`,

    // Authentication
    `.SH AUTHENTICATION`,
    `Authentication can be provided in three ways (in order of precedence):`,
    `.TP`,
    `1. Command-line flag: --token`,
    `.TP`,
    `2. Environment variable: ${nameUpper.replace(/-/g, "_")}_TOKEN`,
    `.TP`,
    `3. Config file: ~/.config/${model.name}/config.json`,
    ``,
    generateSecuritySchemesMan(model),

    // Environment
    `.SH ENVIRONMENT`,
    `.TP`,
    `.B ${nameUpper.replace(/-/g, "_")}_TOKEN`,
    `API authentication token.`,

    // Files
    `.SH FILES`,
    `.TP`,
    `.I ~/.config/${model.name}/config.json`,
    `Configuration file storing persistent settings like API token and base URL.`,

    // Examples
    `.SH EXAMPLES`,
    generateExamplesMan(model),

    // See Also
    `.SH SEE ALSO`,
    `.BR curl (1),`,
    `.BR jq (1)`,

    // Authors
    `.SH AUTHORS`,
    `Generated by ocliporter from OpenAPI specification.`,
  ];

  return sections.join("\n");
}

function generateConfigCommandsMan(cliName: string): string {
  return `.SS config
Manage CLI configuration.
.TP
.B ${cliName} config set \\fIkey\\fR \\fIvalue\\fR
Set a configuration value.
.TP
.B ${cliName} config get \\fIkey\\fR
Get a configuration value.
.TP
.B ${cliName} config list
List all configuration values.
.TP
.B ${cliName} config delete \\fIkey\\fR
Delete a configuration value.`;
}

function generateResourceMan(name: string, description: string, commands: Command[], cliName: string): string {
  const lines: string[] = [
    `.SS ${name}`,
    escapeTroff(description),
  ];

  for (const cmd of commands) {
    const pathParams = cmd.params.filter((p) => p.location === "path");
    const queryParams = cmd.params.filter((p) => p.location === "query");
    const args = pathParams.map((p) => `\\fI${escapeTroff(p.name)}\\fR`).join(" ");

    lines.push(`.TP`);
    lines.push(`.B ${cliName} ${name} ${cmd.name} ${args}`.trim());
    lines.push(escapeTroff(cmd.description));

    if (pathParams.length > 0) {
      lines.push(`.RS`);
      for (const p of pathParams) {
        lines.push(`.TP`);
        lines.push(`.I ${escapeTroff(p.name)}`);
        lines.push(`${escapeTroff(p.description)} (${p.type}${p.required ? ", required" : ""})`);
      }
      lines.push(`.RE`);
    }

    if (queryParams.length > 0) {
      lines.push(`.RS`);
      lines.push(`Options:`);
      for (const p of queryParams) {
        lines.push(`.TP`);
        lines.push(`.BR \\-\\-${escapeTroff(p.name)} " " \\fI${p.type}\\fR`);
        lines.push(escapeTroff(p.description));
      }
      lines.push(`.RE`);
    }
  }

  return lines.join("\n");
}

function generateSecuritySchemesMan(model: CLIModel): string {
  if (model.securitySchemes.length === 0) return "";

  const lines: string[] = [`Supported authentication methods:`];

  for (const scheme of model.securitySchemes) {
    lines.push(`.TP`);
    lines.push(`.B ${scheme.type}`);
    if (scheme.type === "bearer") {
      lines.push(`Bearer token authentication. Pass token via --token flag.`);
    } else if (scheme.type === "apiKey") {
      lines.push(`API key authentication via ${scheme.location || "header"} (${scheme.paramName || "X-API-Key"}).`);
    } else if (scheme.type === "basic") {
      lines.push(`HTTP Basic authentication.`);
    }
  }

  return lines.join("\n");
}

function generateExamplesMan(model: CLIModel): string {
  const lines: string[] = [];

  // Config example
  lines.push(`.TP`);
  lines.push(`Set up authentication:`);
  lines.push(`.RS`);
  lines.push(`.nf`);
  lines.push(`$ ${model.name} config set token "your-api-token"`);
  lines.push(`.fi`);
  lines.push(`.RE`);

  // Resource examples
  for (const resource of model.resources.slice(0, 2)) {
    for (const cmd of resource.commands.slice(0, 2)) {
      const pathParams = cmd.params.filter((p) => p.location === "path");
      const args = pathParams.map((p) => `<${escapeTroff(p.name)}>`).join(" ");

      lines.push(`.TP`);
      lines.push(`${escapeTroff(cmd.description)}:`);
      lines.push(`.RS`);
      lines.push(`.nf`);
      lines.push(`$ ${model.name} ${resource.name} ${cmd.name} ${args}`.trim());
      lines.push(`.fi`);
      lines.push(`.RE`);
    }
  }

  return lines.join("\n");
}
